/* 
* Copyright (c) 2018 - Lox Game Studio. All rights reserved.
* Developed by: LordOf Xen
*/

/*
* Generated with Lox Javascript Generator from Turkish to English.
*/
var english =
{
    "title": "Lox Game Studio",
    "copyright": "Copyright &copy; 2018 - Lox Game Studio. All rights reserved.<br>All trademarks are the property of their respective owners in the US and other countries.",
    "backtolox": "Home Page",
    "bots": "Bots",
    "about": "About",
    "guides": "Guides",
    "joinus": "Join us!",
    "joinustxt": "If you want to help our team with the development of our bots and support us, you can simply join our Discord group and/or help us by providing feedback.",
    "privacyt": "Privacy Policy",
    "termst": "Terms of Service",
    "donateus":"Donation",
    "joinsupportg": "Support",
    "patreonmsg":"If you love one of our services, games, APIS, libraries or bots, please don't forget to support for more features. ",
    "tab_wi": "Lox Security Bot",
    "tab_htsu": "How To Install",
    "tab_cmds": "Commands",
    "tab_domains": "Detected Domain Names",
    "msgBox_cancel": "Cancel",
    "msgBox_ok": "Got it.",
    "wilsb01": "What Does Lox Security Bot Do?",
    "wilsb01_02": "Lox Security Bot has been developed to prevent bad stuff from happening in the server in your absence. As an example, while you are working on a different task someone who wanted to advertise stuff (Names that include group invites etc.) joined your server, if it goes unnoticed by the server moderators or the owner itself it is possible for that person to stay in the server for a while, right? But they have forgotten something, Lox Security Bot was made exactly to fight these kind of problems, in your absence anyone who joins the server to advertise stuff will be automatically kicked out of the server, and the owner will be notified by the bot.</br>Also, anyone who has a swear word on their names will also be kicked automatically by the bot.</br></br>There is also another algorithm we use to improve the security of the server. If a user that joined the server has been created in the past 24 hours, the server owner will be notified with a relevant description.</br></br>One of the most important features of Lox Security Bot is the fact that every message that gets sent will be checked in our servers. If a message contains a dangerous link or a possible scamming website, the message will be deleted in no time and the person who sent the message will be warned.</br></br>You can also use our bot to manually scan websites.</br></br>In addition to that, you can report other \"users\" to Lox Security Bot, making it possible for other Lox Security Bot users to be noticed if someone who got blacklisted or reported joins their server. To see how it works you can check the image below.</br>If someone who got blacklisted joins your server, we will automatically kick them out and inform you about why he was reported.</br>A discord user who got blacklisted will not be able to send messages in any of the servers that contains Lox Security Bot.",
    "htsu01": "After adding Lox Security Bot to your server, you must use one of the commands below to activate some features which comes disabled by default.<br><span class=\"cmd-span\">&gt;detectblacklistedusers</span><br><span class=\"cmd-span\">&gt;detectfakeaccounts</span><br><span class=\"cmd-span\">&gt;detectadsonusername</span><br>Other than that, there is nothing you have to do.</br>If the bots prefix character is conflicting with another bot in your server, you can use >setprefix to change it.</br></br>You can add the bot to your group by clicking <a href=\"https://discordapp.com/oauth2/authorize?client_id=492021132938182658&scope=bot&permissions=76806\" target=\"_blank\">here</a>. </br></br><a href=\"https://discordbots.org/bot/492021132938182658\"><img src=\"https://discordbots.org/api/widget/status/492021132938182658.svg\" alt=\"Security Bot\"/></a>",
    "htsu01_01": "How to use Lox Security Bot?",
    "htsu02_02": "Additional Info",
    "htsu02": "Lox Security Bot requires some permissions to be able to use all of its features. While adding the bot if you do not give it the permission to be able to delete messages, it cannot delete the malicious links from your server.</br>If any problem happens in the process you will be notified automatically. In case of the problems being not fixed some of the features might get broken or might not work at all.</br></br>Lox Game Studios respects your privacy and will not watch any messages directly, or share it on anywhere else.",
    "lcolcmd": "Command",
    "lcoldesc": "Description",
    "lcolperm": "Permissions",
    "cmdst": "Commands",
    "cmdhelpdesc": "Shows the description and examples of a command, and when used alone it will list all of the commands.",
    "cmdhelpperms": "Everyone",
    "cmdprfxdesc": "Changes the prefix character. you can change it if its conflicting with another bots prefix character. ",
    "cmdprfxperms": "Moderator or server owner",
    "cmdreportudesc": "Reports the stated user to us. Reporting a user will help with other servers to not go through the same problems you have gone through with the reported user, and improves the security of the servers. If there is a user that you want to report, you can report them by writing their username or ID along with this command.</br>We want to make clear that the users who gets reported wont be added to the blacklist immediately, and will be checked by Lox Game Studio beforehand.",
    "cmdreportuperms": "Everyone",
    "cmdreportocdesc": "You can manually check the websites by using this command. Websites that gets scanned with this command will also be checked up with VirusTotal afterwards as an extra step.</br>We strongly advise you to spend some time checking the links that gets sent to you instead of opening them directly.",
    "cmdreportocperms": "Everyone",

    "cmdblacklistedusers": "Enables or disables the blacklisted user detection system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdblacklistedusersperms": "Moderator or server owner",

    "cmdfakeaccounts": "Enables or disables the fake account detection system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdfakeaccountsperms": "Moderator or server owner",

    "cmdadsonusername":"Enables or disables the ad detection on username system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdadsonusernameperms": "Moderator or server owner",

    "lcmdprefix": "Default prefix character: <span class=\"lx-panel-p-span-prefix\">&gt; (Customizable)</span>",
    "cmdsext": "Examples",
    "lcolsamp": "Example",
    "cmdhelpsamp": "&gt;help or &gt;help \"setprefix\"",
    "cmdprfxsamp": "&gt;setprefix \"test\"",
    "cmdreportusamp": "&gt;reportuser \"Wumpus\"",
    "cmdreportocsamp": "&gt;reportorcheck \"www.example.com\"",
        "cmdblacklisteduserssamp": "&gt;detectblacklistedusers 1",
    "cmdfakeaccountssamp": "&gt;detectfakeaccounts 1",
    "cmdadsonusernamesamp": "&gt;detectadsonusername 1",
    "domainst": "Detected Malicious Domain Names",
    "domainstext": "We detected \"210.000\" malicious domain names to this day, and we would be happy to share some of the detected malicious domains with you.</br>There are a few lists that we have created specially for you. But we want to make it clear that these lists only contains 10.636 of these malicious domain names.",
    "domainslistt": "Malicious Domain Name Lists",
    "mdlitem01": "Text File",
    "mdlitem02": "XML File",
    "mdlitem03": "JSON File",
    "mdlitem04": "SQL INSERT File",
    "msgboxTitle01": "Warning",
    "aboutlox": "Lox Game Studio is an independent game development team that has been founded in Turkey, but without being strictly limited to making games, they also develop varied bots, libraries, applications, and API's. In 2012 the studio firstly founded in the name of Lox Studio and then got renamed into Lox Game Studio in 2015.",
    "msgboxMessage01": "Lox Game Studio will now direct you to the malicious domain names list. Please do not press any of the links that the list provides.</br>Otherwise Lox Game Stuido will not take any responsibility."
};

/*
* Generated with Lox Javascript Generator.
*/
var german =
{
    "title": "Lox Game Studio",
    "patreonmsg":"If you love one of our services, games, APIS, libraries or bots, please don't forget to support for more features. ",
    "copyright": "Urheberrecht & Kopie; 2018 - Lox Game Studio. Alle Rechte vorbehalten <br> Alle Marken sind Eigentum ihrer jeweiligen Besitzer in den USA und anderen Ländern.",
    "backtolox": "Startseite",
    "joinus": "Begleiten Sie uns!",
    "joinustxt": "Wenn Sie möchten, dass unser Team Lox Security Bot entwickelt, können Sie das Projekt unterstützen, indem Sie sich unserer Gruppe Discord anschließen.",
    "bots": "Bots",
    "about": "Über",
    "donateus":"Spende",
    "privacyt": "Datenschutz-Bestimmungen",
    "termst": "Nutzungsbedingungen",
    "guides": "Führungen",
    "joinsupportg": "Support",
    "tab_wi": "Lox Sicherheits-Bot",
    "tab_htsu": "Information zum Installieren",
    "tab_cmds": "Befehle",
    "tab_domains": "Erkannte Domainnamen",
    "msgBox_cancel": "Abbrechen",
    "msgBox_ok": "Verstanden.",
    "wilsb01": "Was macht Lox Sicherheits-Bot?",
    "wilsb01_02": "Lox Sicherheits-Bot wurde entwickelt, um zu verhindern, dass in Ihrer Abwesenheit auf dem Server schlimme Dinge passieren. Als Beispiel, während Sie an einer anderen Aufgabe arbeiten, ist jemand, der Dinge werben wollte (Namen, die Gruppeneinladungen usw. einschließen) Ihrem Server beigetreten, wenn es von den Servermoderatoren oder dem Besitzer selbst unbemerkt bleibt, ist es für diese Person möglich eine weile auf den Server zu bleiben richtig? Aber sie haben etwas vergessen, Lox Sicherheits-Bot wurde genau dafür gemacht, diese Art von Problemen zu bekämpfen, in Ihrer Abwesenheit wird jeder, der dem Server beitritt, um Werbung zu machen, automatisch aus dem Server geworfen und der Besitzer wird vom Bot benachrichtigt </br> Außerdem wird jeder, der ein Schimpfwort auf seinen Namen hat, automatisch vom Bot gekickt.</br></br>Es gibt auch einen anderen Algorithmus, den wir verwenden, um die Sicherheit des Servers zu verbessern. Wenn ein Benutzer, der dem Server beigetreten ist, in den letzten 24 Stunden erstellt wurde, wird der Serverbesitzer mit einer entsprechenden Beschreibung benachrichtigt.</br></br>Eine der wichtigsten Eigenschaften von Lox Sicherheits-Bot ist die Tatsache, dass jeder Nachrichten in einen gefährlichen Link oder mögliche Scamming-Website enthält, wird die Nachricht in kürzester Zeit gelöscht und die Person, die die Nachricht gesendet hat, wird gewarnt. </br> </br> Zusätzlich können Sie andere Berichte erstellen.",
    "htsu01": "Nachdem Sie Lox Security Bot zu Ihrem Server hinzugefügt haben, müssen Sie einen der folgenden Befehle verwenden, um einige Funktionen zu aktivieren, die standardmäßig deaktiviert sind.<br><span class=\"cmd-span\">&gt;detectblacklistedusers</span><br><span class=\"cmd-span\">&gt;detectfakeaccounts</span><br><span class=\"cmd-span\">&gt;detectadsonusername</span><br>Wenn das Bots-Präfix Zeichen mit einen anderen Bot in Konflikt steht Ihr Server kann mit> setpräfix geändert werden. </br> </br> Sie können den Bot zu Ihrer Gruppe hinzufügen, indem Sie <a href=\"https://discordapp.com/oauth2/authorize?client_id=492021132938182658&scope=bot&permissions=76806\" target=\"_blank\">hier</a>. </br></br><a href=\"https://discordbots.org/bot/492021132938182658\"><img src=\"https://discordbots.org/api/widget/status/492021132938182658.svg\" alt=\"Security Bot\"/></a> klicken.",
    "htsu01_01": "Wie benutzt man den Lox Sicherheits-Bot?",
    "htsu02_02": "Zusätzliche Infos",
    "htsu02": "Lox Sicherheits-Bot benötigt einige Berechtigungen, um alle Funktionen nutzen zu können. Wenn Sie den Bot hinzufügen, wenn Sie ihm nicht die Erlaubnis geben, Nachrichten löschen zu können, kann er die schädlichen Links von Ihrem Server nicht löschen.</br>Wenn dabei ein Problem auftritt, werden Sie automatisch benachrichtigt. Im Falle, dass die Probleme nicht behoben werden, können einige der Features kaputt gehen oder gar nicht funktionieren. </br> </br> Lox Game Studios respektiert Ihre Privatsphäre und wird keine Nachrichten direkt ansehen oder irgendwo anders teilen.",
    "lcolcmd": "Befehl",
    "lcoldesc": "Beschreibung",
    "lcolperm": "Berechtigungen",
    "cmdst": "Befehle",
    "cmdhelpdesc": "Zeigt die Beschreibung und Beispiele eines Befehls an, und wenn er allein verwendet wird, werden alle Befehle aufgelistet.",
    "cmdhelpperms": "Jeder",
    "cmdprfxdesc": "Ändert das Präfixzeichen. Sie können es ändern, wenn es mit einem anderen Bots-Präfixzeichen in Konflikt steht.",
    "cmdprfxperms": "Moderator oder Serverbesitzer",
    "cmdreportudesc": "Meldet den angegebenen Benutzer zu uns. Das Melden eines Benutzers wird dazu beitragen, dass andere Server die gleichen Probleme, die Sie mit dem gemeldeten Benutzer durchgemacht haben, nicht mehr durchlaufen und die Sicherheit der Server verbessern. Wenn es einen Benutzer gibt, den Sie melden möchten, können Sie ihn melden, indem Sie seinen Benutzernamen oder seine ID zusammen mit diesem Befehl schreiben. </br> Wir möchten klarstellen, dass die Benutzer, die gemeldet werden, nicht sofort zur Blacklist hinzugefügt werden wird vorher von Lox Game Studio überprüft.",
    "cmdreportuperms": "Jeder",
    "cmdreportocdesc": "Sie können die Websites manuell mit diesem Befehl überprüfen. Websites, die mit diesem Befehl gescannt werden, werden anschließend als zusätzlicher Schritt mit VirusTotal überprüft.</br>Wir empfehlen Ihnen dringend, einige Zeit damit zu verbringen, da an Sie gesendeten Links zu überprüfen, anstatt sie direkt zu öffnen.",
    "cmdreportocperms": "Jeder",

    "cmdblacklistedusers": "Enables or disables the blacklisted user detection system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdblacklistedusersperms": "Moderator oder Serverbesitzer",

    "cmdfakeaccounts": "Enables or disables the fake account detection system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdfakeaccountsperms": "Moderator oder Serverbesitzer",

    "cmdadsonusername":"Enables or disables the ad detection on username system. Please type 1 or 0 to enable or disable this property. For more information, do not hesitate to contact us.",
    "cmdadsonusernameperms": "Moderator oder Serverbesitzer",

    "lcmdprefix": "Standard Präfix Zeichen: <span class=\"lx-panel-p-span-prefix\">&gt; (ersetzbar)</span>",
    "cmdsext": "Beispiele",
    "lcolsamp": "Beispiel",
    "cmdhelpsamp": "&gt;help or &gt;help \"setprefix\"",
    "cmdprfxsamp": "&gt;setprefix \"test\"",
    "cmdreportusamp": "&gt;reportuser \"Wumpus\"",
    "cmdreportocsamp": "&gt;reportorcheck \"www.example.com\"",

    "cmdblacklisteduserssamp": "&gt;detectblacklistedusers 1",
    "cmdfakeaccountssamp": "&gt;detectfakeaccounts 1",
    "cmdadsonusernamesamp": "&gt;detectadsonusername 1",

    "domainst": "Erkannte bösartige Domönennamen",
    "domainstext": "Wir haben bis heute \"210.000\" bösartige Domainnamen entdeckt, und wir würden gerne einige der entdeckten bösartigen Domains mit Ihnen teilen. </br> Es gibt ein paar Listen, die wir speziell für Sie erstellt haben. Aber wir möchten klarstellen, dass diese Liste nur 10.636 dieser bösartigen Domainnamen enthält.",
    "domainslistt": "Liste bösartiger Domainnamen",
    "mdlitem01": "Textdatei",
    "mdlitem02": "XML-Datei",
    "mdlitem03": "JSON-Datei",
    "mdlitem04": "SQL-INSERT-Datei",
    "msgboxTitle01": "Warnung",
    "aboutlox": "Lox Game Studio is an independent game development team that has been founded in Turkey, but without being strictly limited to making games, they also develop varied bots, libraries, applications, and API's. In 2012 the studio firstly founded in the name of Lox Studio and then got renamed into Lox Game Studio in 2015.",
    "msgboxMessage01": "Lox Game Studio leitet Sie nun zur Liste der bösartigen Domainnamen. Bitte drücken Sie keine der Links, die die Liste bietet. </br> Andernfalls Lox Game Studio übernimmt keine Verantwortung."
};

var turkish = 
{
    "title": "Lox Oyun Stüdyosu", 
    "patreonmsg":"Hizmetlerimizden, oyunlarımızdan, API'lerden, kütüphanelerimizden veya botlarımızdan birini seviyorsanız, lütfen daha fazla özellik için desteklemeyi unutmayın. ",
    "copyright": "Telif Hakkı &copy; 2018 - Lox Game Studio. Tüm hakları saklıdır.<br>Tüm ticari markalar ABD ve diğer ülkelerdeki kendi sahiplerinin mülkiyetindedir.",
    "backtolox": "Ana Sayfa",
    "bots": "Botlar",
    "about": "Hakkında",
    "joinus": "Bize katılın!",
    "joinustxt": "Ekibimize botlarımızın gelişimi konusunda yardımcı olmak ve bize destek çıkmak isterseniz, Discord grubumuza katılabilir ve/veya geribildirim sağlayarak bize yardımcı olabilirsiniz.",
    "privacyt": "Gizlilik Politikası",
    "guides": "Kılavuzlar",
    "termst": "Kullanım Şartları",
    "donateus": "Bağış",
    "joinsupportg": "Destek",
    "tab_wi": "Lox Güvenlik Botu",
    "tab_htsu": "Nasıl Kurulur",
    "tab_cmds": "Komutlar",
    "tab_domains": "Tespit Edilen Alan Adları",
    "msgBox_cancel": "İptal",
    "msgBox_ok": "Anladım devam et.",
    "wilsb01": "Lox Güvenlik Botu Ne İşe Yarar?",   
    "wilsb01_02": "Lox Güvenlik Botu, yokluğunuz sırasında grubunuzda olabilecek kötü olayları engellemek için geliştirilmiştir. Örneğin, siz başka bir iş ile uğraşırken sunucunuza istenmeyen reklamları (Örn. Grup davetleri içeren Kullanıcı isimleri) göstermek için bir Discord kullanıcısı katıldı, her hangi bir moderatörünüz veya sizin tarafından tespit edilmediği süreç içerisinde bu kullanıcının grubunuzda bir süre kalması mümkün olacaktır, değil mi? Ama unuttukları bir şey var, Lox Güvenlik Botu tam bu tür problemlerle başa çıkmak için geliştirildi. Sizin yokluğunuzda sunucunuza reklam yapmak için gelen kullanıcılar (Kullanıcı adında reklam barındıran) otomatik olarak gruptan atılacaktır ve grup sahibine bir bildirim gönderilecektir.</br>Aynı zamanda, kullanıcı adında küfür içeren kullanıcıları da otomatik olarak gruptan atacaktır.</br></br>Sunucu güvenliğini arttırmak için bizim kullandığımız bir başka algoritma daha var. Eğer sunucunuza giren kullanıcı hesabı 24 saat içerisinde oluşturmuş ise, sunucu sahibine açıklaması ile birlikte bir bildirim mesajı gönderilir.</br></br>Lox Güvenlik Botunun en önemli özelliklerinden bir tanesi, grubunuzda gönderilen tüm mesajların sunucularımız tarafından taranmasıdır. Sunucunuz içerisinde gönderilen mesajlar eğer tehlikeli bir bağlantıyı veya dolandırıcılık sitelerini içeriyorsa, otomatik olarak mesaj silinecektir ve gönderene bir uyarı mesajı gönderilecektir.</br></br>Botumuzu kullanarak siteleri manuel olarak da kontrol ettirebilirsiniz.</br></br>Ayrıca, Lox Güvenlik Botuna Discord kullanıcılarını rapor edebilirsiniz, böylece diğer grup sahiplerine otomatik olarak bir bildirim gidecektir. Nasıl çalıştığını görmek için aşşağıdaki resime bakabilirsiniz.</br>Eğer karalisteye alınan bir Discord kullanıcısı her hangi bir davet linki ile grubunuza katılmaya çalışırsa, biz otomatik olarak onu atacağız ve sizlere sebebini söyleyeceğiz.</br>Kara listeye alınan bir Discord kullanıcısı Lox Güvenlik Botunun olduğu her hangi bir grupta mesaj gönderemez.",
    "htsu01": "Lox Security Bot'u sunucunuza ekledikten sonra, varsayılan olarak devre dışı bırakılan bazı özellikleri etkinleştirmek için aşağıdaki komutlardan birini kullanmanız gerekir.<br><span class=\"cmd-span\">&gt;detectblacklistedusers</span><br><span class=\"cmd-span\">&gt;detectfakeaccounts</span><br><span class=\"cmd-span\">&gt;detectadsonusername</span><br>Bunun dışında yapmanız gereken bir şey yoktur.</br>Eğer botun prefix karakteri grubunuzdaki başka bir bot ile çakışıyorsa, >setprefix ile değiştirebilirsiniz.</br></br><a href=\"https://discordapp.com/oauth2/authorize?client_id=492021132938182658&scope=bot&permissions=76806\" target=\"_blank\">Buraya</a> tıklayarak botu grubunuza ekleyebilirsiniz.</br></br><a href=\"https://discordbots.org/bot/492021132938182658\"><img src=\"https://discordbots.org/api/widget/status/492021132938182658.svg\" alt=\"Security Bot\"/></a>",
    "htsu01_01":"Lox Güvenlik Botu Nasıl Kullanılır?",
    "htsu02_02": "Ek Bilgi",
    "htsu02": "Lox Güvenlik Botunu tüm özellikleri ile kullanabilmeniz için gerekli izinlere ihtiyacı vardır. Botu eklerken mesajları silme iznini vermezseniz, bot sunucunuzdaki tehlikeli bağlantıları silemez.</br>İşlem sırasında oluşan sorunlar sizlere otomatik olarak bildirilecektir. Ve giderilmediği taktirde bazı özelliklerin çalışmasını bozabilir veya hiç çalışmayabilir.</br></br>Lox Oyun Stüdyosu gizliliğinize saygı duyar ve hiçbir mesajı izlemez, ve her hangi bir yerde yayınlanmaz.",
    "lcolcmd": "Komut",
    "lcoldesc":  "Açıklama",
    "lcolperm": "İzinler",
    "cmdst": "Komutlar",
    "cmdhelpdesc": "Bir komutun açıklamasını ve örneklerini gösterir veya direkt olarak yazıldığında tüm komutları listeler.",
    "cmdhelpperms": "Herkes",
    "cmdprfxdesc": "Prefix karakterini değiştirir. Eğer başka bir botun prefix karakteri ile çakışıyorsa, değiştirebilirsiniz.",
    "cmdprfxperms": "Moderatör veya sunucu sahibi",
    "cmdreportudesc": "Belirtilen kullanıcıyı bizlere bildirir. Bir kullanıcıyı bildirmek, diğer sunucuların sizin bildirilen kullanıcı ile yaşadığınız sorunların aynısını yaşamamasını sağlar, ve sunucularda güvenliği arttırır. Eğer bildirmeniz gereken bir kullanıcı varsa, bu komut ile kullanıcı ismini veya ID yazarak bildirebilirsiniz.</br>Bildirilen her kullanıcının otomatik olarak karalisteye alınmadığını ve Lox Oyun Stüdyosu tarafından kontrol edildiğini de belirtmek isteriz.",
    "cmdreportuperms": "Herkes",
    "cmdreportocdesc": "Bu komut ile manuel olarak websitelerini kontrol ettirebilirsiniz. Bu komut ile kontrol ettirilen websiteleri, extra olarak VirusTotal ile de kontrol ettirilecektir.</br>Sizlere gönderilen adresi direkt olarak tıklayıp girmek yerine biraz zaman ayırıp incelemenizi şiddetle tavsiye ederiz.",
    "cmdreportocperms": "Herkes",

    "cmdblacklistedusers": "Kara listeye alınmış kullanıcı tespit sistemini etkinleştirir veya devre dışı bırakır. Bu mülkü etkinleştirmek veya devre dışı bırakmak için lütfen 1 veya 0 yazın. Daha fazla bilgi için, bizimle iletişim kurmaktan çekinmeyin.",
    "cmdblacklistedusersperms": "Moderatör veya sunucu sahibi",

    "cmdfakeaccounts": "Sahte hesap saptama sistemini etkinleştirir veya devre dışı bırakır. Bu mülkü etkinleştirmek veya devre dışı bırakmak için lütfen 1 veya 0 yazın. Daha fazla bilgi için, bizimle temas kurmaktan çekinmeyin.",
    "cmdfakeaccountsperms": "Moderatör veya sunucu sahibi",

    "cmdadsonusername":"Kullanıcı adı sistemindeki reklam tespitini etkinleştirir veya devre dışı bırakır. Bu mülkü etkinleştirmek veya devre dışı bırakmak için lütfen 1 veya 0 yazın. Daha fazla bilgi için, bizimle temas kurmaktan çekinmeyin.",
    "cmdadsonusernameperms": "Moderatör veya sunucu sahibi",

    "lcmdprefix": "Varsayılan prefix karakteri: <span class=\"lx-panel-p-span-prefix\">&gt; (Değiştirilebilir)</span>",
    "cmdsext": "Örnekler",
    "lcolsamp": "Örnek",
    "cmdhelpsamp": "&gt;help veya &gt;help \"setprefix\"",
    "cmdprfxsamp": "&gt;setprefix \"test\"",
    "cmdreportusamp": "&gt;reportuser \"Wumpus\"",
    "cmdreportocsamp": "&gt;reportorcheck \"www.example.com\"",
        "cmdblacklisteduserssamp": "&gt;detectblacklistedusers 1",
    "cmdfakeaccountssamp": "&gt;detectfakeaccounts 1",
    "cmdadsonusernamesamp": "&gt;detectadsonusername 1",
    "domainst": "Tespit Edilen Zararlı Alan Adları",
    "domainstext": "Bugüne kadar 210 bin zararlı alan adı tespit ettik ve sunucumuza ekledik. Bu tespit edilen zararlı alan adlarının bir kısmını sizlerle paylaşmaktan mutluluk duyarız.</br>Sizlere özel olarak hazırladığımız listeler var. Ama listelerin sadece 10636 zararlı alan adını içerdiğini de belirtmek isteriz.</br>",
    "domainslistt": "Zararlı Alan Adı Listeleri",
    "mdlitem01": "Metin Dosyası",
    "mdlitem02": "XML Dosyası",
    "mdlitem03": "JSON Dosyası",
    "mdlitem04": "SQL INSERT Dosyası",
    "msgboxTitle01": "Uyarı",
    "aboutlox": "Lox Oyun Stüdyosu, Türkiye'de kurulmuş bağımsız bir oyun geliştirme ekibidir, ancak oyun yapmakla sınırlı kalmadan, çeşitli botlar, kütüphaneler, uygulamalar ve API'lar geliştirir. 2012 yılında stüdyo ilk olarak Lox Stüdyosu adına kuruldu ve 2015 yılında Lox Game Studio olarak yeniden adlandırıldı.",
    "msgboxMessage01": "Lox Oyun Stüdyosu sizi zararlı alan adı listesine yönlendirecektir. Açılan sayfadaki hiçbir linke tıklayıp girmeyin.</br>Aksi halde Lox Oyun Stüdyosu sorumluluk kabul etmemektedir."
};