/* 
* Copyright (c) 2018 - Lox Game Studio. All rights reserved.
* Developed by: LordOf Xen
*/

/*
* Generated with Lox Javascript Generator from Turkish to English.
*/
var english =
{
    "title": "Lox Game Studio",
    "copyright": "Copyright &copy; 2018 - Lox Game Studio. All rights reserved.<br>All trademarks are the property of their respective owners in the US and other countries.",
    "backtolox": "Home Page",
    "joinsupportg": "Support",
    "tab_wi": "Lox Security Bot",
    "tab_htsu": "How To Install",
    "tab_cmds": "Commands",
    "tab_domains": "Detected Domain Names",
    "msgBox_cancel": "Cancel",
    "msgBox_ok": "Got it.",
    "wilsb01": "What Does Lox Security Bot Do?",
    "wilsb01_02": "Lox Security Bot has been developed to prevent bad stuff from happening in the server in your absence. As an example, while you are working on a different task someone who wanted to advertise stuff (Names that include group invites etc.) joined your server, if it goes unnoticed by the server moderators or the owner itself it is possible for that person to stay in the server for a while, right? But they have forgotten something, Lox Security Bot was made exactly to fight these kind of problems, in your absence anyone who joins the server to advertise stuff will be automatically kicked out of the server, and the owner will be notified by the bot.</br>Also, anyone who has a swear word on their names will also be kicked automatically by the bot.</br></br>There is also another algorithm we use to improve the security of the server. If a user that joined the server has been created in the past 24 hours, the server owner will be notified with a relevant description.</br></br>One of the most important features of Lox Security Bot is the fact that every message that gets sent will be checked in our servers. If a message contains a dangerous link or a possible scamming website, the message will be deleted in no time and the person who sent the message will be warned.</br></br>You can also use our bot to manually scan websites.</br></br>In addition to that, you can report other \"users\" to Lox Security Bot, making it possible for other Lox Security Bot users to be noticed if someone who got blacklisted or reported joins their server. To see how it works you can check the image below.</br>If someone who got blacklisted joins your server, we will automatically kick them out and inform you about why he was reported.</br>A discord user who got blacklisted will not be able to send messages in any of the servers that contains Lox Security Bot.",
    "htsu01": "There is nothing else you have to do make activate Lox Security Bot after adding it to your server, after it gets added to the server it will be automatically up and running.</br>If the bots prefix character is conflicting with another bot in your server, you can use >setprefix to change it.</br></br>You can add the bot to your group by clicking <a href=\"https://discordapp.com/oauth2/authorize?client_id=492021132938182658&scope=bot&permissions=76806\" target=\"_blank\">here</a>. </br></br><a href=\"https://discordbots.org/bot/492021132938182658\"><img src=\"https://discordbots.org/api/widget/status/492021132938182658.svg\" alt=\"Security Bot\"/></a>",
    "htsu01_01": "How to use Lox Security Bot?",
    "htsu02_02": "Additional Info",
    "htsu02": "Lox Security Bot requires some permissions to be able to use all of its features. While adding the bot if you do not give it the permission to be able to delete messages, it cannot delete the malicious links from your server.</br>If any problem happens in the process you will be notified automatically. In case of the problems being not fixed some of the features might get broken or might not work at all.</br></br>Lox Game Studios respects your privacy and will not watch any messages directly, or share it on anywhere else.",
    "lcolcmd": "Command",
    "lcoldesc": "Description",
    "lcolperm": "Permissions",
    "cmdst": "Commands",
    "cmdhelpdesc": "Shows the description and examples of a command, and when used alone it will list all of the commands.",
    "cmdhelpperms": "Everyone",
    "cmdprfxdesc": "Changes the prefix character. you can change it if its conflicting with another bots prefix character. ",
    "cmdprfxperms": "Moderator or server owner",
    "cmdreportudesc": "Reports the stated user to us. Reporting a user will help with other servers to not go through the same problems you have gone through with the reported user, and improves the security of the servers. If there is a user that you want to report, you can report them by writing their username or ID along with this command.</br>We want to make clear that the users who gets reported wont be added to the blacklist immediately, and will be checked by Lox Game Studio beforehand.",
    "cmdreportuperms": "Everyone",
    "cmdreportocdesc": "You can manually check the websites by using this command. Websites that gets scanned with this command will also be checked up with VirusTotal afterwards as an extra step.</br>We strongly advise you to spend some time checking the links that gets sent to you instead of opening them directly.",
    "cmdreportocperms": "Everyone",
    "lcmdprefix": "Default prefix character: <span class=\"lx-panel-p-span-prefix\">&gt; (Customizable)</span>",
    "cmdsext": "Examples",
    "lcolsamp": "Example",
    "cmdhelpsamp": "&gt;help or &gt;help \"setprefix\"",
    "cmdprfxsamp": "&gt;setprefix \"test\"",
    "cmdreportusamp": "&gt;reportuser \"Wumpus\"",
    "cmdreportocsamp": "&gt;reportorcheck \"www.example.com\"",
    "domainst": "Detected Malicious Domain Names",
    "domainstext": "We detected \"210.000\" malicious domain names to this day, and we would be happy to share some of the detected malicious domains with you.</br>There are a few lists that we have created specially for you. But we want to make it clear that these lists only contains 10.636 of these malicious domain names.",
    "domainslistt": "Malicious Domain Name Lists",
    "mdlitem01": "Text File",
    "mdlitem02": "XML File",
    "mdlitem03": "JSON File",
    "mdlitem04": "SQL INSERT File",
    "msgboxTitle01": "Warning",
    "msgboxMessage01": "Lox Game Studio will now direct you to the malicious domain names list. Please do not press any of the links that the list provides.</br>Otherwise Lox Game Stuido will not take any responsibility."
};

var turkish = 
{
    "title": "Lox Oyun Stüdyosu", 
    "copyright": "Telif Hakkı &copy; 2018 - Lox Game Studio. Tüm hakları saklıdır.<br>Tüm ticari markalar ABD ve diğer ülkelerdeki kendi sahiplerinin mülkiyetindedir.",
    "backtolox": "Ana Sayfa",
    "joinsupportg": "Destek",
    "tab_wi": "Lox Güvenlik Botu",
    "tab_htsu": "Nasıl Kurulur",
    "tab_cmds": "Komutlar",
    "tab_domains": "Tespit Edilen Alan Adları",
    "msgBox_cancel": "İptal",
    "msgBox_ok": "Anladım devam et.",
    "wilsb01": "Lox Güvenlik Botu Ne İşe Yarar?",   
    "wilsb01_02": "Lox Güvenlik Botu, yokluğunuz sırasında grubunuzda olabilecek kötü olayları engellemek için geliştirilmiştir. Örneğin, siz başka bir iş ile uğraşırken sunucunuza istenmeyen reklamları (Örn. Grup davetleri içeren Kullanıcı isimleri) göstermek için bir Discord kullanıcısı katıldı, her hangi bir moderatörünüz veya sizin tarafından tespit edilmediği süreç içerisinde bu kullanıcının grubunuzda bir süre kalması mümkün olacaktır, değil mi? Ama unuttukları bir şey var, Lox Güvenlik Botu tam bu tür problemlerle başa çıkmak için geliştirildi. Sizin yokluğunuzda sunucunuza reklam yapmak için gelen kullanıcılar (Kullanıcı adında reklam barındıran) otomatik olarak gruptan atılacaktır ve grup sahibine bir bildirim gönderilecektir.</br>Aynı zamanda, kullanıcı adında küfür içeren kullanıcıları da otomatik olarak gruptan atacaktır.</br></br>Sunucu güvenliğini arttırmak için bizim kullandığımız bir başka algoritma daha var. Eğer sunucunuza giren kullanıcı hesabı 24 saat içerisinde oluşturmuş ise, sunucu sahibine açıklaması ile birlikte bir bildirim mesajı gönderilir.</br></br>Lox Güvenlik Botunun en önemli özelliklerinden bir tanesi, grubunuzda gönderilen tüm mesajların sunucularımız tarafından taranmasıdır. Sunucunuz içerisinde gönderilen mesajlar eğer tehlikeli bir bağlantıyı veya dolandırıcılık sitelerini içeriyorsa, otomatik olarak mesaj silinecektir ve gönderene bir uyarı mesajı gönderilecektir.</br></br>Botumuzu kullanarak siteleri manuel olarak da kontrol ettirebilirsiniz.</br></br>Ayrıca, Lox Güvenlik Botuna Discord kullanıcılarını rapor edebilirsiniz, böylece diğer grup sahiplerine otomatik olarak bir bildirim gidecektir. Nasıl çalıştığını görmek için aşşağıdaki resime bakabilirsiniz.</br>Eğer karalisteye alınan bir Discord kullanıcısı her hangi bir davet linki ile grubunuza katılmaya çalışırsa, biz otomatik olarak onu atacağız ve sizlere sebebini söyleyeceğiz.</br>Kara listeye alınan bir Discord kullanıcısı Lox Güvenlik Botunun olduğu her hangi bir grupta mesaj gönderemez.",
    "htsu01": "Lox Güvenlik Botunu grubunuza eklemek dışında aktif hale getirmek için yapmanız gereken herhangi bir şey yoktur. Siz grubunuza ekledikten sonra otomatik olarak kendi çalışmaya başlayacaktır.</br>Eğer botun prefix karakteri grubunuzdaki başka bir bot ile çakışıyorsa, >setprefix ile değiştirebilirsiniz.</br></br><a href=\"https://discordapp.com/oauth2/authorize?client_id=492021132938182658&scope=bot&permissions=76806\" target=\"_blank\">Buraya</a> tıklayarak botu grubunuza ekleyebilirsiniz.</br></br><a href=\"https://discordbots.org/bot/492021132938182658\"><img src=\"https://discordbots.org/api/widget/status/492021132938182658.svg\" alt=\"Security Bot\"/></a>",
    "htsu01_01":"Lox Güvenlik Botu Nasıl Kullanılır?",
    "htsu02_02": "Ek Bilgi",
    "htsu02": "Lox Güvenlik Botunu tüm özellikleri ile kullanabilmeniz için gerekli izinlere ihtiyacı vardır. Botu eklerken mesajları silme iznini vermezseniz, bot sunucunuzdaki tehlikeli bağlantıları silemez.</br>İşlem sırasında oluşan sorunlar sizlere otomatik olarak bildirilecektir. Ve giderilmediği taktirde bazı özelliklerin çalışmasını bozabilir veya hiç çalışmayabilir.</br></br>Lox Oyun Stüdyosu gizliliğinize saygı duyar ve hiçbir mesajı izlemez, ve her hangi bir yerde yayınlanmaz.",
    "lcolcmd": "Komut",
    "lcoldesc":  "Açıklama",
    "lcolperm": "İzinler",
    "cmdst": "Komutlar",
    "cmdhelpdesc": "Bir komutun açıklamasını ve örneklerini gösterir veya direkt olarak yazıldığında tüm komutları listeler.",
    "cmdhelpperms": "Herkes",
    "cmdprfxdesc": "Prefix karakterini değiştirir. Eğer başka bir botun prefix karakteri ile çakışıyorsa, değiştirebilirsiniz.",
    "cmdprfxperms": "Moderatör veya sunucu sahibi",
    "cmdreportudesc": "Belirtilen kullanıcıyı bizlere bildirir. Bir kullanıcıyı bildirmek, diğer sunucuların sizin bildirilen kullanıcı ile yaşadığınız sorunların aynısını yaşamamasını sağlar, ve sunucularda güvenliği arttırır. Eğer bildirmeniz gereken bir kullanıcı varsa, bu komut ile kullanıcı ismini veya ID yazarak bildirebilirsiniz.</br>Bildirilen her kullanıcının otomatik olarak karalisteye alınmadığını ve Lox Oyun Stüdyosu tarafından kontrol edildiğini de belirtmek isteriz.",
    "cmdreportuperms": "Herkes",
    "cmdreportocdesc": "Bu komut ile manuel olarak websitelerini kontrol ettirebilirsiniz. Bu komut ile kontrol ettirilen websiteleri, extra olarak VirusTotal ile de kontrol ettirilecektir.</br>Sizlere gönderilen adresi direkt olarak tıklayıp girmek yerine biraz zaman ayırıp incelemenizi şiddetle tavsiye ederiz.",
    "cmdreportocperms": "Herkes",
    "lcmdprefix": "Varsayılan prefix karakteri: <span class=\"lx-panel-p-span-prefix\">&gt; (Değiştirilebilir)</span>",
    "cmdsext": "Örnekler",
    "lcolsamp": "Örnek",
    "cmdhelpsamp": "&gt;help veya &gt;help \"setprefix\"",
    "cmdprfxsamp": "&gt;setprefix \"test\"",
    "cmdreportusamp": "&gt;reportuser \"Wumpus\"",
    "cmdreportocsamp": "&gt;reportorcheck \"www.example.com\"",
    "domainst": "Tespit Edilen Zararlı Alan Adları",
    "domainstext": "Bugüne kadar 210 bin zararlı alan adı tespit ettik ve sunucumuza ekledik. Bu tespit edilen zararlı alan adlarının bir kısmını sizlerle paylaşmaktan mutluluk duyarız.</br>Sizlere özel olarak hazırladığımız listeler var. Ama listelerin sadece 10636 zararlı alan adını içerdiğini de belirtmek isteriz.</br>",
    "domainslistt": "Zararlı Alan Adı Listeleri",
    "mdlitem01": "Metin Dosyası",
    "mdlitem02": "XML Dosyası",
    "mdlitem03": "JSON Dosyası",
    "mdlitem04": "SQL INSERT Dosyası",
    "msgboxTitle01": "Uyarı",
    "msgboxMessage01": "Lox Oyun Stüdyosu sizi zararlı alan adı listesine yönlendirecektir. Açılan sayfadaki hiçbir linke tıklayıp girmeyin.</br>Aksi halde Lox Oyun Stüdyosu sorumluluk kabul etmemektedir."
};